# Generated by Django 6.0.5 on 2026-09-21 13:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('MESSAGE', 'Message'), ('FRIEND', 'Friend')], max_length=10)),
                ('entity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='api_notific_recipie_28b188_idx'), models.Index(fields=['recipient', 'created_at'], name='api_notific_recipie_913487_idx')],
            },
        ),
    ]
