services:
  # Port non expose sur l'hote (surface d'attaque reduite).
  # Decommenter le mapping 8200:8200 pour deboguer l'UI Vault localement.
  vault:
    image: hashicorp/vault:2.0
    container_name: vault
    cap_add:
      - IPC_LOCK
    env_file: .env
    networks:
      - transcendence-network

  postgres:
    image: postgres:15-alpine
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - transcendence-network

  redis:
    image: redis:7-alpine
    restart: always
    networks:
      - transcendence-network

  mailpit:
      image: axllent/mailpit:latest
      container_name: mailpit
      restart: always
      networks:
        - transcendence-network

  backend:
    build: ./backend
    restart: always
    env_file: .env
    volumes:
      - ./backend:/app # Hot-reload : on lie le code local au container
      - ./backend/media:/app/media
    depends_on:
      - postgres
      - redis
      - vault
      - mailpit
    networks:
      - transcendence-network

  frontend:
    build: ./frontend
    restart: always
    volumes:
      - ./frontend:/app # Hot-reload
      - /app/node_modules # evite que le node_modules local écrase celui du container
    networks:
      - transcendence-network

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:8080"   # HTTP -> redirect 301 vers HTTPS
      - "443:8443"  # HTTPS (WAF actif)
    environment:
      MODSEC_RULE_ENGINE: ${MODSEC_RULE_ENGINE:-On}
      MODSEC_AUDIT_ENGINE: RelevantOnly
      MODSEC_AUDIT_LOG: /dev/stdout
      MODSEC_AUDIT_LOG_FORMAT: JSON
      BLOCKING_PARANOIA: ${BLOCKING_PARANOIA:-1}
      DETECTION_PARANOIA: ${DETECTION_PARANOIA:-1}
      ANOMALY_INBOUND: ${ANOMALY_INBOUND:-5}
      ALLOWED_METHODS: "GET HEAD POST OPTIONS PUT PATCH DELETE"
      MODSEC_REQ_BODY_LIMIT: 13107200
      MODSEC_REQ_BODY_NOFILES_LIMIT: 131072
      PORT: 8080
      SSL_PORT: 8443
      SERVER_NAME: localhost
      SSL_CERT_FILE: /etc/nginx/conf/server.crt
      SSL_CERT_KEY_FILE: /etc/nginx/conf/server.key
    volumes:
      - ./nginx/templates/conf.d/default.conf.template:/etc/nginx/templates/conf.d/default.conf.template:ro
      - ./nginx/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf:/etc/modsecurity.d/owasp-crs/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf:ro
      - ./nginx/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf:/etc/modsecurity.d/owasp-crs/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf:ro
      - ./backend/media:/app/media:ro
    depends_on:
      - backend
      - frontend
    networks:
      - transcendence-network

volumes:
  postgres_data:

networks:
  transcendence-network:
    driver: bridge
